name: BeastTP
main: code.husky.BeastTP
version: 2.1
commands:
        to:
           description: Tp's Sender to Target
        from:
           description: Tp's Target to Sender
        sto:
           description: Tp's Target to Sender Silent
        sfrom:
           description: Tp's Target to Sender Silent
        dto:
           description: Disable tp
        dfrom:
           description: Disable tp           